name: Contentful Broken Link Checker

on:
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest
    environment: StagingUnprotected

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install export-processor deps
        working-directory: ./contentful/export-processor/
        run: npm ci

      - name: Install dependencies
        working-directory: ./contentful/broken-link-checker/
        run: npm ci

      - name: Run checker
        working-directory: ./contentful/broken-link-checker/
        env:
          MANAGEMENT_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          USE_PREVIEW: false
          SPACE_ID: ${{ secrets.SPACE_ID }}
          CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
        run: npm run checker
